version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  project: Wox.Plugin.Todos.sln
after_build:
  - ps: cd Wox.Plugin.Todos\bin\Release; 7z a Wox.Plugin.Todos.zip
artifacts:
- path: 'Wox.Plugin.Todos\bin\Release\Wox.Plugin.Todos.zip'
  name: Wox.Plugin.Todos
